/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Root;

/**
 *
 * @author dashb
 */
public class Root extends javax.swing.JFrame {

    /**
     * Creates new form Bodega_Root
     */
    public Root() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegRoot = new javax.swing.JButton();
        btnRegAdm = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnBuscarRoot = new javax.swing.JButton();
        btnModiPerf = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        btnDatosPerf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegRoot.setBackground(new java.awt.Color(255, 153, 51));
        btnRegRoot.setForeground(new java.awt.Color(51, 0, 51));
        btnRegRoot.setText("Registrar Root");
        btnRegRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegRootActionPerformed(evt);
            }
        });

        btnRegAdm.setBackground(new java.awt.Color(255, 153, 51));
        btnRegAdm.setForeground(new java.awt.Color(51, 0, 51));
        btnRegAdm.setText("Registrar Administrador");
        btnRegAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAdmActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(255, 153, 102));
        btnReportes.setForeground(new java.awt.Color(51, 51, 0));
        btnReportes.setText("Acceso a Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnBuscarRoot.setBackground(new java.awt.Color(255, 153, 102));
        btnBuscarRoot.setForeground(new java.awt.Color(51, 51, 0));
        btnBuscarRoot.setText("Búsqueda por Root");
        btnBuscarRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRootActionPerformed(evt);
            }
        });

        btnModiPerf.setBackground(new java.awt.Color(255, 153, 51));
        btnModiPerf.setForeground(new java.awt.Color(51, 0, 51));
        btnModiPerf.setText("Modificar Perfiles ");
        btnModiPerf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiPerfActionPerformed(evt);
            }
        });

        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        btnDatosPerf.setBackground(new java.awt.Color(255, 153, 102));
        btnDatosPerf.setForeground(new java.awt.Color(51, 51, 0));
        btnDatosPerf.setText("Datos de Perfiles");
        btnDatosPerf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosPerfActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Tiene que estar la hora\nEl Día, rol, nombre y apellidos\nNombre del Sistema, Versión\nAño, licencia privada, contacto, soporte técnico, objetivo del sistema\nLugar de la programación, logo de la empresa");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDatosPerf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModiPerf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModiPerf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatosPerf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegRootActionPerformed

  dispose();        
        Registrar_Root p =new Registrar_Root();
           p.setVisible(true);        
           
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegRootActionPerformed

    private void btnRegAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAdmActionPerformed

        dispose();        
        Registrar_Administrador o =new Registrar_Administrador();
           o.setVisible(true);        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegAdmActionPerformed

    private void btnModiPerfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiPerfActionPerformed

             dispose();        
        Modificar_Perfiles eo =new Modificar_Perfiles();
           eo.setVisible(true);        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnModiPerfActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
                  dispose();        
        Acceso_Reportes eq =new Acceso_Reportes();
           eq.setVisible(true);        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnDatosPerfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosPerfActionPerformed

              dispose();        
        Datos_Perfiles ef =new Datos_Perfiles();
           ef.setVisible(true);        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnDatosPerfActionPerformed

    private void btnBuscarRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRootActionPerformed

             dispose();        
        Busqueda_Root ew =new Busqueda_Root();
           ew.setVisible(true);        

// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarRootActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed

System.exit(0);        
// TODO add your handling code here:
    }//GEN-LAST:event_btnDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Root.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Root.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Root.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Root.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Root().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRoot;
    private javax.swing.JButton btnDatosPerf;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnModiPerf;
    private javax.swing.JButton btnRegAdm;
    private javax.swing.JButton btnRegRoot;
    private javax.swing.JButton btnReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
