/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author dashb
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Bodega_Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnGuardarPass = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("                  SGI BODEGA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(177, 11, 199, 31);

        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Ingrese Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(353, 60, 223, 27);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(23, 93, 171, 28);

        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Ingrese Usuario ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 60, 223, 27);

        btnIngresar.setBackground(new java.awt.Color(255, 153, 0));
        btnIngresar.setFont(new java.awt.Font("Microsoft New Tai Lue", 2, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(23, 127, 171, 48);

        btnGuardarPass.setBackground(new java.awt.Color(0, 51, 51));
        btnGuardarPass.setFont(new java.awt.Font("Microsoft New Tai Lue", 2, 14)); // NOI18N
        btnGuardarPass.setForeground(new java.awt.Color(51, 153, 255));
        btnGuardarPass.setText("Recordar Contraseña");
        getContentPane().add(btnGuardarPass);
        btnGuardarPass.setBounds(353, 127, 171, 48);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(350, 90, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarPass;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
